import Head from "next/head";
import Title from "../components/Title";

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Next Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4">
        <Title>Next Shop</Title>

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>
      </main>

      <footer className="p-2">
        <p>Next Shop</p>
      </footer>
    </div>
  );
};

export default Home;
