import Head from "next/head";
import { ReactChildren } from "react";
import Title from "../components/Title";
import { getProducts, Product } from "../lib/products";

export async function getStaticProps() {
  console.log("[getStaticProps()]");
  const products = await getProducts();
  return { props: { products } };
}

interface Props {
  children?: React.ReactNode;
  products: Array<Product>;
}

const Home: React.FC = ({ products }: Props) => {
  return (
    <div>
      <Head>
        <title>Next Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4">
        <Title>Next Shop</Title>
        <h2 className="text-lg font-bold pb-2">Products</h2>
        <ul>
          {products.map(({ id, title }) => (
            <li key={id}>{title}</li>
          ))}
        </ul>
      </main>

      <footer className="p-2">
        <p>Next Shop</p>
      </footer>
    </div>
  );
};

export default Home;
