import Head from "next/head";
import Image from "next/image";

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Next Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Next Shop!</h1>

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>
      </main>

      <footer>
        <p>Next Shop</p>
      </footer>
    </div>
  );
};

export default Home;
